name: Gradle Build
on: [push, pull_request, merge_group]

jobs:
  build:
    name: Build WorldEdit on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: 'temurin'

    - name: Make gradle wrapper executable
      run: chmod +x ./gradlew

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        cache-read-only: ${{ !(github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/version/')) }}

    - name: Execute Gradle build
      run: ./gradlew build -s

    - name: Upload WorldEdit jar
      uses: actions/upload-artifact@v4
      with:
        name: WorldEdit-Folia-Snapshot
        path: build/libs/*
